/**
 * Book content for The Phenomenology of Culture-Systems.
 * Chapters store full text; the reader paginates by viewport height at runtime.
 */

/**
 * @param {{ text?: string, pages?: string[] }} chapter
 * @returns {string}
 */
export function getChapterText(chapter) {
  if (typeof chapter.text === 'string') return chapter.text;
  if (Array.isArray(chapter.pages)) return chapter.pages.join('\n\n');
  return '';
}

export const BOOK_ID = 'phenomenology-culture-systems-v1';
export const BOOK_TITLE = 'The Phenomenology of Culture-Systems';
export const BOOK_SUBTITLE =
  'Volume 1: Grand Synthesis: Mythology of the 21st Century (2018)';

export const CHAPTERS = [
  {
    id: 'proem',
    title: 'Proem: First Epistle to the Highbrows',
    pages: [
      `Pray thee, take care, that tak’st my book in hand
To read it well—that is, to understand.

1 The professor of philosophy and religion Jacob Needleman once pointed out that there are two basic types of prefaces, one written before the text and thus lengthy, full of the strength, vision, and hope of the authors, the other written after the text and thus brief, a manifestation of the authors’ realization of their limitations. Needleman offered the analogy of the minister of renown who condescended to give a sermon in the church of a struggling young minister. The authoritative man proudly ascended to the lofty pulpit and spoke grandly for an hour, only to then realize that by the time he had finished, half the congregation had walked out and the other half was asleep. The great man humbly descended from the pulpit and meekly asked his colleague what he had done wrong. “Had you ascended in the way that you descended,” he answered, “then you might have descended in the way that you ascended.” With professor Needleman’s wise words in mind, we have written the following before and after writing the text, in the sincere hope of expressing the vision and humility of the authors in undertaking such a momentous task. The search for Wisdom is almost always forsaken by gods and the masses, the former based on knowledge and the latter based on ignorance. Thus the task falls upon us, who are not gods nor just animals, but that tenuous intermediate level of existence, Mankind. A research writer need not be trained in everything under the sun, but he or she must have ability in the abstract and demonstrate it pragmatically. Piece out our imperfections with your thoughts (Shakespeare). The following text is the core document of the Noödynamics Institute. It will be best understood in its multiple layers if it be read sequentially, and has been structured so as to allow easy return-access to those needing many sittings to complete the reading. We have taken some liberties with our titles and hope readers will`,
      `accept the practice with the sense of mirth with which it was applied. After all, how many readers would be inspired to read The Kyphotic Campanologist of the Seat of the Diocesan Bishop of Paris?

2 Because we are trying to shed a particular light on our ideological viewpoint as well as to provide a preface to it, this proem has certain definite limitations. For instance, this is not a comprehensive introduction. In other words, we do not attempt, in a step-by-step fashion, to summarize all the major positions taken in the following volumes. This is, rather, a philosophical preface: an attempt to explain our approach to the text. Moreover, we make little effort to defend our interpretations against rivals. The reader should be aware of the fact that for virtually every claim we make in the volumes that follow, there are conflicting claims by thoughtful, serious scholars who would offer different interpretations. Although we could defend our claims at greater length in step-by-step analysis, we cannot do so here without abandoning our purpose. But we do not mind. The point of this proem is never to give the reader a boiled-down summary of each of the volumes nor to give him or her an absolutely definite overview, but to enable the reader to go on and read these volumes. Our views inevitably color the presentation of ideas, theories, and`,
      `arguments, but we have striven to present contending concepts fairly, and, whenever we endorse or reject one of them, have tried to give sufficient reason for doing so. Noödynamics, like philosophy itself, is first and last an exercise in reason, and the ideas that should prevail in our discourse are those which have the best reasons on their sides. If this text is successful, readers will learn enough to assess where the weight of reason rests. Every expository work makes some demand upon the readers’ sympathies.

In addressing their subject, authors take an attitude toward it and adopt a tone they believe to be apropos. The sense of what is apropos, either in attitude or tone, is of course a question of values. The demand upon readers’ sympathies may be made explicitly or implicitly, but there can be no expostulations without some sort of sympathetic contract between writers and readers. We have chosen to make our demands explicit, because we are taking the subject of our work as a matter of major consequence.

If the Noödynamics Institute is to succeed, our readers must be willing to sympathize with our attitude toward Culture and with our tone toward Academia. Whatever differences one may feel between themselves and the authors in matters of detail, we want to leave no ambiguity concerning our sympathetic contract. It is common of a text of this type to preface it with methodological statements concerning one’s understanding of the enterprise of cultural philosophy, its distinction from other intellectual enterprises such as sociology, standards for evaluating its level of success, and so on. We shall pass over such issues here, primarily because our approach is so novel and our theories so unorthodox that little of value could be put forth at a general level at this point.

Each of the volumes below, as a matter of fact, effectively answers such questions in a different and unique way— each offers its own account of the way in which a culture expresses itself, and its own account of the criteria for the successful transmission of knowledge. Evaluating any particular method of attaining, sustaining, and transmitting knowledge, therefore, cannot be extracted from, or done in advance of, evaluating substantive theories of cultural expression. As for possible criteria by which Academia can judge the success of`,
      `the Noödynamics Institute in the enterprise of cultural philosophy, we believe that the ultimate test of our admittedly unorthodox theories will be whether or not they cohere with, and help to illuminate, the nature of the institutions they seek to explicate. If on reflection we share the intuition that cultures are systemic phenomena, then it is a powerful objection to proposed epistemological theories of reductionism or globalism, for example. Similarly, if our theory of philosophy matches considered intuitions, and structures them so as to bring out their internal logic, then we have a powerful argument in favor of that novel theory. Of course, these intuitions may be baseless, but that is beside the point.

The fact is that we have these intuitive senses, and we deem it rational and natural to attempt to work out their implications, searching for integrated and coherent conceptualizations of value. Of course, some will argue that there is no way to organize intuitive senses into systematic principles; that they derive from tacit understanding or unconscious impulses and any attempt to formalize these intuitions into abstract principles distorts them and produces empty formulae. To be sure, we have great empathy for such views. Nevertheless, we believe that these intuitive senses are amenable to discursive examination, and thus that they can be organized into systemic and systematic principles capable of further meaningful interpretation.

In the final analysis, we believe that the only way of rationally defending a comprehensive theory of culture is by providing particular arguments for a particular theory, and in the volumes which follow we advance arguments that we deem to be compelling enough to justify our methodological assumptions. Whether or not we succeed is for our readers to decide. There will be many who do not understand the nature of the type of abstractions we utilize. But then, after all, unfortunately, there are many who do not understand the nature of any type of logical argument.

Indeed, we believe there are fewer people now alive who truly understand logical argument than there were during any other period in history; and thus this text might have been better received by any century`,
      `before the 21st . Argument is long and complex, and being resolved to argue, to argue honestly, to answer all relevant questions, to deal with every significant issue, we have produced a text that is too long and intricate to be popular. We have aimed for an intellectual aristocracy; for a stupendous certitude, in the presence of which, all libraries of postmodern commentary will be but collections of pamphlets. “Every effect that one produces gives one an enemy,” declared Oscar Wilde. ” It took us over two decades to produce this book and we wish we could have taken three.

However, if we had waited long enough to be intellectually satisfied with the preparation we would probably never have written it at all. ” Certainly we do not make this claim now; with each passing year we have come to learn that there is much more to learn, in what may very well be a process interminable in a lifetime; but alas we know things which are of necessity now, and thus we just wrote about them. ” This is in fact a text wherein the social and aesthetic intentions are inextricably mingled; wherein the form and the dramatic psychology of the text show the clear pressure of our social feelings. We hope our readers will find here an instance of T. S. Eliot’s description of our aesthetic development as a series of wholly new attempts and concomitant new kinds of failure. If we succeed in anything extra-ordinary, it shall be inextricably bound up with imperfection. This is a text`,
      `wherein content and structure are inseparable; wherein introspective drama and reflective analysis must be addressed at the same time. Here it must be noted that successful exegesis consists not merely in content but also in expression; in significant form–form giving substance to the matter it forms. Let thy chief terror be of thine own soul. We have made every effort to negotiate a careful middle path between oversimplified generalities and irrelevant particularities, and where we have failed, will not stoop to the common practice of defending either with presumptuous and pious espousals of a primary desire to provoke debate.

Our first and last aim is to communicate a message we deem of unrivaled significance, and hopefully our thematic devotion to an architectonic Philosophy of Science will beguile those specialized in the various fields to pardon the liberties necessarily taken with regard to profoundly complex subjects. As R. G. Collingwood observed, we can understand a text only when we understand the question to which it is an answer. This text ventures from theoretic principles to practical facts and back again, ad infinitum, and therefore it occasionally gives a strong sense of infinitely reducible specificity eluding coherent general definition, and so we implore readers to make an effort to follow our ariadnic thread through the labyrinthine struggle betwixt impressionistic taxonomy and arabesque minutiae.

These points are important because there must inevitably be a shift in perspective between, on the one hand, the exploration of fields and theories and facts that are amenable to cogent delineation because they are fully developed and formalized as such— regardless of interpretation—automatically convey a sense of objectivity and, on the other hand, that of nascent and emerging fields and theories and facts which are no less “scientific” but are as yet inchoate and subject to significant interpretive conceptualizations. The issue at stake is not so much the viability and credibility of specific sophisticated hypotheses, as recognition that the known influences and colors our search for and comprehension of the unknown. It is therefore important to maintain some clarity as to the epistemological presuppositions. Such a notion may seem at first glance to be unduly`,
      `pedantic, but it will become especially and increasingly germane as one progresses through the volumes. We are supremely aware of our debt to a host of scholars of every nation of the West who have illuminated with their touch almost every topic in this text. The scope of the present text does not allow of reference to the multitude of masters and specialists whose work has been used. Readers familiar with the subjects will see without difficulty when we are following a well-known authority, when we are using or criticizing a number of detached studies, and when in a few places the arguments and/or conclusions rest upon a re-assessment of the original sources.

“Sometimes a mere article or essay,” explained American philosopher Suzanne K. Langer, “can give one’s thinking a new slant or suddenly organize one’s scattered knowledge into a significant idea, yet be completely swallowed up in the theories it has influenced so that no specific reference can be made to it at any particular point of their exposition. ” For example, in Volume 2, the chapter on Physics was written first. Then the chapter on Psychology was written, and the chapter on Physics was rewritten to incorporate the chapter on Psychology.

Then the chapter on Biology was written, and the chapters on Physics and Psychology were rewritten to incorporate the chapter on Biology. Then the chapter on Cognitive Theory was written, and the chapters on Physics, Psychology, and Biology were rewritten to incorporate the chapter on Cognitive Theory, and so on, for all chapters and all volumes. The text has been extensively annotated for purposes of both academic depth and artistic enrichment. All Academics are more learned in some fields than in others.

In a wide-ranging text such as this, even a multi-disciplinary team of Academics must rely on the work of specialists and popularizers alike. Obviously, for the myriad topics covered herein, this material constitutes a wealth of information so unimaginably vast as to be beyond the possible knowledge of any handful of individuals. Much`,
      `of this text is therefore secondand even third-hand, derived from the works of other Academics who before us sought to gather various disciplines and ideas into harmonious syncretic wholes. In order to fulfill the expressive, persuasive, referential, and literary purpose of this project, as well as to stimulate the P-300 brainwaves of our readers, every time we have set ink to paper (or electron to magnetic storage medium), with scholia and euphuism, we have tried to steer a literary course between parataxis and hypotaxis; all that is written, said William Caxton, is written for our doctrine. Such a text must inevitably contain academic errors. More specifically, it must contain foreshortenings which experts will regret and oversights which technicians will bemoan.

We have used an inordinate number of quotes in the text because it is much more of a synthesis than an original creation. We are the builders not the architects. Yet having been significantly written based on secondary sources and even memory, there will inevitably be omitted attributions and credits. The myriad ideas in this book have been accumulated over the course of decades and sometimes their sources have simply been forgotten. We welcome instruction from readers who recognize such omissions, and have provided a full bibliography as a guide to further study.

The specific object of this text is alternative interpretation; the general object, what the French call haute vulgarisation: The positive popularization in which the obscurity of over-technical verbiage is eliminated but the material nevertheless maintains its intellectual integrity. Its ideal reader is that theoretical construct, the intelligent and educated (including autodidactic) person, who is not only still capable of thinking for himself, but has the natural desire to understand what Western Culture is, what its place in the World and History means, and what may be expected and hoped for in the Future. As Nathaniel Hawthorne related in 1850: The truth seems to be... that, when he casts his leaves forth upon the wind, the author addresses, not the many who will fling aside his volume, or never take it up, but the few who`,
      `will understand him, better than most of his schoolmates or lifemates. It would therefore be pedantic and pretentious to overload the text with the advanced information which would interest more learned readers. On the other hand, it would be coarse and counter-productive to fail to present the expert evidence supporting the theses offered herein. An attempt has been made to address both of these necessities, presenting specific cutting-edge discoveries and esoteric information, without losing the general theme in the profundities of specialization.

Substantial concretization (Ingarden &amp; Vodkka) is required. This is an open work (Eco). We have, in preparing this tome, been repeatedly reminded of Marianne Moore, who when told that her poetry is difficult to read, explained that it was also difficult to write. We are our own metaphor. We have flatly rejected the 20th Century will-to-impoverishment in the use of language. We strive not just to use the English language correctly, but also to use it well. To accomplish this, we spent a lot of time realizing the basic quality of words.

They are qualities not simply of grammatical use but of words in a meaningful context. As Oliver Wendall Holmes observed, a word is “the skin of a living thought” and hence may vary greatly according to particular use. The Noödynamics Institute urged its writers to make deliberate and impassioned use of these qualities, which embody the living force of the language. Once one becomes aware of these qualities, the very nature of the language is transformed. Hence, below you will not find the simplest synonym, nor the most straight-forward sentence structure, nor short über-concise paragraphs.

We commonly selected language for its connotation rather than for its denotation, paying acute attention to the various forces within the words and the possible richness entailed in diverse juxtapositions. For the language-sensitive, every word has its own aura. We have felt our words richly in terms of their root sense and sensuously in terms of the apperceptions they compel, always concerned with the way our words work in context with one another.`,
      `The communication of meaning is an involvement. The reader must be made to enter the writer’s state of mind in telling detail. Long, complex sentences may be seen, therefore, as the long way around, yet as the most direct line to reader involvement. What must be edited from a work is not extra words, but those parts which, if any, do not serve to involve the reader. The best conductor is not the person who can lead an orchestra through Wagner’s Ring cycle in the shortest elapsed time, but the one who can bring the orchestra and the audience to the fullest involvement in the music.

It is the density of suggestion that counts. The best argument is not the shortest verbal line between two points, but the best completely involving line. You will find herein long sentences without Tolstoyan excesses; compound subjects and predicates without Faulknerian abuses; and no Twainian hyperbole. The covers are too far apart, but due to the urgency of our message, we did not have time to write a short thesis and so wrote a long one. Like all cultural expressions, this text has its own destiny tuum est.

” These ideas are, however, presented in a new light, a new context, and a new lifeview. Much of psychical evolution occurs due to the recombination of ideas. The minority of ideas that are new in this text are presented in a highly unorthodox paradigm, but each has been supported by substantial orthodox and hard science. ” We want to be strong poets. Yet like Thomas Aquinas, we can write no more; we have seen things that make all our writings like chaff. The activist-scholar gives people what they need rather than what they want.

In this sense the activist-scholar is an antidote; indeed, he or she is often opposed because he or she is mistaken for a poison because he or she is an antidote. The activist-scholar improves the world by focusing on whatever the world neglects, which changes in every period. And the other history-shapers recognize the work of the activist-`,
      `scholar by a type of instinct. The next generation must be, paradoxically, converted by the activist-scholars who contradict it most. It is necessary to make Academia understand anew the use of understanding—the West needs activists; but above all, it needs scholars. Our movement resembles the growth of a plant, which by its own force thrust its leaves out into the sunlight. We are seeking to do the most unpopular thing that humans can do: start a popular movement. Our goal has been a work that acts on others.

We do not write, as have most Postmodernists, simply for the sake of writing. We write in the interest of action. Even Science, after all, is impeded by repressive dogmatism, and thus requires action for freedom as much as it does research. We do not seek to teach, but only to create conditions conducive to learning: un exercise extraordinaire! The habit-oriented anticipation of the smartest group on earth must be exposed and overcome. Thus we accept Faust’s starting dictum: In the beginning was the Deed.

The extent to which this text would be annotated, both factually and artistically, was a matter of some debate. ) so that no reader will be left unsure as to our meanings, and readers desiring no such addition or expansion may simply surpass them. The annotation is of two basic types: corollary and collateral. The corollary notes explore and expand ideas and concepts; collateral notes offer cognate ideas and concepts, usually from different domains than the one under discussion. If a reader objects to, or is interested in, any statement, these notes are available as extra material for consideration.

We are not succumbing to a perverse eclecticism but simply acknowledging a problem Marlowe memorably addressed in Tamberlaine (1581): Had fed the feelings of their master’s thoughts, And every sweetness then inspired their hearts, Their minds, and muses, on admired themes—If all the heavenly quintessence they ‘still`,
      `From their immortal flowers of poesy, Wherein, as in a mirror, we perceive The highest reaches of human wit—If those had made one poem’s period, And all combined in beauty’s worthiness, Yet should there hover in our restless heads One thought, one grace, one wonder, at the least, Which into words no virtue can digest. The art, poetry, and literature herein have been carefully selected, matched, and assigned; we believe they contribute significantly to understanding the text. Thus while these have been made optional, we recommend that they be incorporated into a thorough reading. ” Similarly, the extensive use of uncommon technical terms is not meant to “show off”— arrogantly proffered archaic or extra-specialized terms, usually depicted as if one is a fool not to know their meanings, is one modern Academic practice we dislike—but rather, to demonstrate that even our most highly unorthodox interpretations of facts are not, as some of our detractors will undoubtedly allege, mere inventions of disillusioned and/or embittered Academics; they are, in fact, genuine ideas and terms derived from mainstream Academia—hitherto misapplied or altogether unaddressed.

Our readers will, naturally, find themselves faced with a battery of technical terms that express a number of pervading and difficult ideas, and wherever possible we have annotated with working definitions. These ideas, therefore, combine into an all-embracing system which provides a uniquely favorable framework for the consideration of philosophical problems, and indeed for the consideration of culture-historical problems of every kind. Such a framework of concepts, transcending the interests of particular academic disciplines and offering an understanding of culture-systems at a very general and abstract level, is what is meant when Philosophers talk of an epistemic system. We have always and everywhere worked diligently to avoid terminological inexactitude and syllogistic reasoning based on`,
      `unarticulated major premises, but since to err is human, know well that we have not always and everywhere succeeded, and hope readers will unhesitatingly bring such problematic issues to our attention. There is much abuse of the logical principle that two things equal to the same thing are equal to each other, based on unarticulated major premises, inappropriate minor premises, or terminological inexactitude. The syllogistic principle that If x=y and y=z, then x=z is a mathematical truism not always maintained in the translation to non-mathematical subjects, a fact that postmodern Academics have exploited incessantly. Here is a threadbare dandy: Major premise: The Ku Klux Klan are caucasian racists.

Minor premise: a, b, and c are caucasian. Conclusion: Therefore, a, b, and c are racists. Examples of such pseudo-logic could be found ad infinitum, and a large portion of postmodernism is predicated upon them. Thus we have almost obsessively annotated definitions and almost compulsively fully articulated major premises before proposing minor premises and conclusions, and count on our readers to point out where we have failed to do so. The refutation of faulty syllogisms is a relatively simple matter, utilizing the basic mathematical principle of deriving a product by canceling from both premises the common terms and combining what remains.

The proper minor premise above, for example, must be “a, b, and c are members of the Ku Klux Klan,” so that “Ku Klux Klan” is subsequently dropped and “a, b, and c” and “caucasian racists” combined. In our politically-correct society, however, many Academics, among their number some of the most prominent and respected, simply refuse to be thus constrained by valid logic because it is, in the final analysis, the conclusions, not the premises with which they begin. For example: Major premise: Christianity is unscientific. Minor premise: Christianity is a religion.`,
      `Conclusion: Therefore, religion is unscientific. Beginning with the conclusion as an ideal, many Academics then “prove” premises by using, for example, the fact that the Bible asserts that the universe was created in 4,004 BC. The unarticulated major premise is that “Christianity” and “religion” are effectively synonymous. The fact that many Pagan mythologies posit a universe billions of years old falsifies the predetermined ideal, and so is simply ignored. Most of what passes for “logic” in Academia is directly or indirectly predicated upon such fallacy.

Like Voltaire, we reject this metaphysico-theologo-cosmonigology, and aim for a poetic conciseness. ” asked Poincaré. “For the philosopher or scientist, it is a definition that applies to all the objects to be defined, and applies only to them; it is that which satisfies the rules of logic. ” In our lucubration, we have utilized a few neologisms where common terms are inadequate, but kept this to a minimum. ” Ultimately, because we desire to express both our own ideas and particular concepts of common thought in a succinct manner, we could hardly help inventing some vocabulary.

There can be no logically relevant objection to the invention of some technical terminology, provided that each term has a clearly assignable function which cannot be fulfilled just as well by a preëxisting term. In effect, some of our language may be deemed “semi-artificial,” in that we use ordinary language enriched by technical terms intended to adapt or render new common concepts. Those neologisms which are not simply cases of logical classification will be readily understood in propositional context. ”`,
      `Because the world that we mean to describe and then analyze is complex, so, too, the structure of this text itself. It is composed as an axiomatic treatise, very much in the style of Newton’s Principia. Certain assumptions are made from the beginning. These are the axioms of the system. ” Where such terms are not defined, they are explained, our explanations serving to refine and purify concepts that are often used ambiguously and/or inconsistently. Our conclusions about the world are intended to follow from our initial assumptions, just as Newton’s conclusions follow from his famous axioms and their correlative definitions.

Some of the text below engages in a Derridian interrogation of foundational concepts of various fields, especially where they uphold the authority, as perceived, of disciplines, but only as an affirming problematizing of usual assumptions. We are rethinking the usual, assumed relations between reality and discipline, deconstructing the apparently clear lines between concepts of reality and representation. We simply believe that Academia must examine its own involvement in the transmission of knowledge and the hierarchies of learning. Noödynamics occupies the space of possibility between the abstract ideals of disciplinary authority and attempts to actualize them in full phenomenological embodiment.

We have also, like Walter Scott, “tagged with rhyme and blank verse the subdivisions of this important narrative, in order to seduce your continued attention by powers of composition of stronger attraction” than our own. Similarly, all subsections are specially highlighted with Art and Poetry we believe appropriate for opening and closing topics of great significance. These methods are, we feel, most conducive to the immensity of our quest. No single person could accomplish that at which we aim.

In fact, so vast is the task that we strongly feel that no single era should attempt such. As Mark Twain noted: There are some books that refuse to be written. They stand`,
      `their ground year after year and will not be persuaded. It isn’t because the book is not there and worth being written —it is only because the right form for the story does not present itself. There is only one right form for a story and if you fail to find that form the story will not tell itself. You may try a dozen wrong forms but in each case you will not get very far before you discover that you have not found the right one—then the story will always stop and decline to go any further. We believe, and make the case herein, that the story of this text has been trying to tell itself for at least a hundred years; furthermore, that the newest scientific discoveries and the World Wide Web have offered us, for the first time, the “right form for the story.” This tome, however, has been written by hundreds of men and women, over ten centuries of Western History. We may accurately declare ourselves the editors of the final work. The text has written itself. Some of our detractors will likely reduce this to the claim that this text is the greatest plagiarism since the Old Testament. As with any comprehensive and syncretic work, the charge is understandable—if disingenuous. We have doubts about the old saying that originality is merely unconscious plagiarism, but like most proverbs it certainly contains at least a kernel of truth. As literary critic and Yale professor Harold Bloom proclaimed, “All literature is plagiaristic.” While we certainly do not proffer this text as literature, our aim is certainly literary. “Ideas are cheap,” declared Stephen Jay Gould. “The use of ideas, the systematic construction of a world in their light, is the stuff of intellectual revolutions.” This tome has been written with tears in the heart’s closed bleeding books, and happy rhymes bathed in the brook....”

3 Bloom admonished: That depth of inwardness in a strong writer constitutes the strength that wards off the massive weight of past achievement, lest every originality be crushed before it becomes manifest. Great writing is always rewriting or revisionism and is founded upon a reading that clears`,
      `space for the self, or that so works as to reopen old works to our fresh sufferings. The originals are not original, but that Emersonian irony yields to the Emersonian pragmatism that the inventor knows How to Borrow. Whereas any new and unorthodox interpretation of facts is typically labeled mis-interpretation by the creators and propagators of reigning dogma, the Noödynamics Institute is going to establish the “legitimacy of misinterpretation”—revisionist re-interpretation and the denunciation of the imposture of “authoritative” interpretation. We have tried to observe the sometimes indistinct boundary between research and plagiarism, but it is often difficult to be sure which side of the boundary one is on.

We have, for example, often found insightful explications which, we believed, nevertheless included conclusions that are the opposite of truth. Therefore, we outlined the statements, reversed the argument, then rewrote the same explications accordingly. Just as often, we found excellent explications which, we believed, nevertheless contained an incorrect core principle. Therefore we replaced the core principle with the one we deemed correct, and rewrote the same explication with the`,
      `proper consequent premises. S. Eliot explained that a good poet is more likely to steal than to imitate. Because ideas evolve, rather than being a product of divine creation, so-called plagiarism is necessary—progress implies it. Academic re-interpretation adheres closely to existing ideas and their delineation; uses the phrases, expressions, and words of discoverers and developers, while deleting false interjections and conclusions, replacing them with better ones—like Einstein “plagiarizing” Newton, and Bohr and Heisenberg “plagiarizing” Einstein.

After the intellectual development of the concept of gravity from the mysterious “action at a distance,” to enigmatic distortions in the space-time continuum, to the unimaginable graviton, it became impossible to believe that words or a phrase can be bound forever to an idea. The academic re-appropriation of concepts by Culture cannot be realized without the appropriation of Language itself. “One of the rarest of all intellectual accomplishments that a man can possess is the grand faculty of arranging his ideas,” noted Wilkie Collins. Once accomplished, why would we alter it?

Immune to the envy and pedantry revealed in false charges of “plagiary,” we declare that once an idea has been perfectly expressed—Res judicata. ” But semantically, what is the point, really, of rewriting the entire sentence because of a single factual error by its author? ’ And this subject is simple compared to many we must tend to in the volumes below. Thus, if someone has proposed, intelligently and/or eloquently, that “2+1+1/2+1/4+1/8+1/16+1/32+1/64+1/128+1/256+1/1074+e=5”, then we are going to slightly alter the statement in order to propose that 2+1+1/2+1/4+1/8+1/16+1/32+1/64+1/128+1/256+1/1074+e=4.

We are`,
      `not going to distract the reader from the essential point and our mission by pedantically trying to find an “original” way to make the general proposition. We refuse to rewrite every statement of the last century due to myriad errors, especially when the propositions are well-stated, and therefore we will simply correct them and move on rather than pretend that an author owns the form of a statement even if the content is erroneous. Where authors are correct, we quote, some will say to excess; where they are mistaken, we rectify. Those who want credit for statements must make accurate assertions therein.

Nevertheless, where slight corrections are possible without totally contradicting the ideas of an author, we give credit. Every Mathematician since Leibniz and Newton has “plagiarized” the Calculus because of its usefulness; we merely extend this academic methodology to all realms of intellectual thought. To salvage Western Academia from its downward spiral it is necessary to continually make it more precise, to correct it within the parameters of the New Paradigm, to reformulate it in the light of a 21st Century context—while carefully preserving the history and tradition of ideas. We hope that by conceding this point beforehand, we may force our detractors to critique our ideas rather than circumambulate the real issues by attacking our ontic methodology.

How else to write the autobiography of a High Culture? ” The zenith of our pretension is to offer literary Westerners a general knowledge which, due to its cultural formation and axiological guidance, can truly be called encyclopedic, from the Greek enkyklios paideia: circle of knowledge. An encyclopedic knowledge contains the entire culture summed up in language. Because such knowledge tells us who we are, where we came from, and where we can go, there is something sacred about it. As pretentious as it may seem, we believe that the following tome can be envisaged as a sort of “user’s manual” for the West as a civilization.

It lays the foundation for a “canonical” perspective of the set of assumptions, conclusions, and meanings we call “culture”. In keeping with our organic approach, explained and explicated below, this summa`,
      `has been organized like human memory and imagination—with everything connected to everything else. There are few books designed to explore Culture per se. The present work, in order to undertake this monumental task, was not limited by an imposed uniformity of treatment. Instead, every volume is organized exactly as we would approach the relevant topics in a course of our own design. The result is highly idiosyncratic, ranging from general surveys to specific polemics, orderly analysis to dramatic flourish.

The customary educational material is here, and the necessary critical concepts are introduced, but little is presented in orthodox fashion. Yet the volumes do have a deeper unity, which derives from certain assumptions shared by the authors. We began with the kind of understanding of our subject that makes its study truly valuable, and thus we have experienced two decades of endless work as a source of unending delight. We propose formal analysis to our readers, not as an end in itself, but as a means of widening their range of comprehension and deepening their appreciation of the thing comprehended.

Kant explained: At individual points every philosophical treatise may be open to objections (for it cannot be armed at all points, like a mathematical one), without the organic structure of the system, considered as a whole, being in the least endangered. Only a few people have that versatility of intellect to consider the whole of a system, when it is new; still fewer have an inclination for it, owing to a dislike of innovation. If we take single passages out of their context, and contrast them with each other, it is simple to point out apparent contradictions, especially in a work that progresses as free speech. In the view of those who depend upon the judgment of others, such contradictions may shed upon any work an unfavorable light; but they are easily eliminated by those who have grasped the idea of the whole.`,
      `Deeds are the pulse of time. Not only does every volume directly or indirectly allude to every other, but each essentially explicates and justifies the others and makes comprehensible certain key concepts which must be understood contextually. No volume is an independent creation; each is part of a whole with an existential unity running through the set. Each volume can, of course, be understood by itself, but only up to a point—independently, they each stand, but not in isolation. The internal consistency and unitary overtone are essentially clues to the deeper meanings of the tome, which has even required new translations.

The style of the text depends on crucial leitmotifs—images which are central to the theme and thus emerge again and again—connected by cross-referenced associations and adding dimensions to the meanings. Nevertheless, these works are nowhere procrustean, and beyond thematic intent there has been minimal attempt at literary uniformity. Selection and compression are inevitable in a work of this scope and magnitude, whose reach is ever greater than our grasp. The methodology most useful in writing a syncretic thesis such as that contained herein is to start with a single page—around 600 words; then the page should be rewritten as a thorough essay—perhaps 100 pages; that essay should then be expanded into a large book, say a few thousand pages in several volumes; finally, the thesis should be written as a comprehensive encyclopedia.

The purpose of this unorthodox and life-consuming process is to help avoid losing readers in the minute details of the thesis, and instead, to lead them gradually through the grand sweep of ideas in a form which maintains its core idea. “Is it so difficult,” lamented G. M. ” What follows is the development of the first three of these four stages. When we study Culture, we are both subject and object, observer and participant. It is a little like going to dinner at the house of a cannibal —sometimes one enjoys dinner, sometimes one is dinner.

Despite the problems, we want to study the behavior and interactions of cultural situations in a manner that allows us to simultaneously experience them, such that we are enabled to learn nearly as much about cultural`,
      `principles from experience as a participant as from our analysis as an observer. We want to engage in active learning about Culture, so that pondering the questions is as fruitful as acquiring the answers. The rhythm of this text will be set, therefore, by the alternation between subject and object of inquiry. Only thus can we overcome the modern malaise in which “culture” has become an abstraction with which people have no genuine experience. If after reading a portion of any volume of this text one wants to learn more about topics mentioned therein, more extensive examinations can be found in the volume(s) specific to that topic.

For example, Volume 1 contains an in-depth discussion of the relationships between science, spirituality, and art, and one can find in-depth examinations of science or spirituality or art in Volumes 2, 3, and 4 respectively. This text simply could not be written within the conventional framework of Academia, now become doctrine and dogma which few question. ” And our discussion of how a text like this should be written is not rhetoric —the first draft, so to speak, was exactly two pages long. It was a vague but inspired outline of the new possibilities presented by recent scientific findings, written in 1997, and predicated upon the hypothesis that if we were to carefully redefine science, spirituality, and art in postmodern terms, they would perhaps move back into harmony with each other.

It was a bold but not a novel thesis, and as we began tracing out its implications for these three domains of expression, and then for the disciplines of these domains—physics, psychology, sociology, history, inter alia—the deepest and most inspiring implications of the ideal began to emerge, here and there and everywhere, revealing newer and broader patterns that became more and more fascinating. The result was very likely the most powerful—almost mystical—obsession and consummation of a research project ever experienced, lasting for two decades. “It’s frightening when you’re starting on a new road that no one has been on before,” observed the feminist Betty Friedan. ” It is not in any manner an exaggeration to state that for`,
      `every page that follows, an entire book was used as reference, which explains what some have called the “extreme intensity” of the work, and why it took a large research and writing team two decades to complete. We confess beforehand to a—sometimes overriding—love of language that can lead from philosophy into poetry, but assert as steadfastly that we do not propose giving up the concept of prosaic truth in order to listen to mere intuitions. We have striven for a style of our own and immersed ourselves thoroughly in words, but shall not succumb to the sparkle of brilliant analyses, nor reduce meaning to etymologies. We believe that Academia demands, now more than ever, a disciplined repudiation of semantics and sophistry.

To fulfill this mission, however, we need not be didactic. Intuition can supplement reason best when it renounces the attempt to proffer undemonstrable truths and instead confronts the mind with that which reason can never fully penetrate: Above all, with Mankind’s apparently inexhaustible potential for self-realization. Philosophical principles can never fully represent this aspect of experience and so language must make use of other—all—resources. Mankind is not a bucket but a well, and language must struggle not only to reflect the images on its surface, but also the shadows lurking in its depths.

Language utilized at its full depth involves complexity as profound and as undefinable as that of Culture itself. Hence for us the final question on the topic is, What is the nature of noödynamic language? Of course, the answer depends on the fundamental question of this text: What is the nature of Culture? Ultimately, such questions are fundamental, and fundamental precisely because they are unanswerable. What matters, and what makes us adopt an unorthodox use of language, is that we ask the questions in the most meaningful way possible.

Every day, we live and experience that which we cannot define, and thus we have attempted to write this tome with a sense of the whole language stirring toward richer possibilities than Academia can presently foresee. We strive for a fine excess (Keats). “Words can be like x-rays, if you use them properly,” observed Aldous Huxley—“They’ll go through anything. ” We choose a formal but dialogical,`,
      `emphatic style, with particularized, acute, scholarly but unpretentious critiques—our preference for the language of the heights as distinct from the language of the streets is nowhere incidental. In one sense words are distinct units. In another sense, however, they shape-shift into rhythmic phrases wherein the words themselves become parts of larger units. This is the basic process in all language and we have often emulated the Poet’s rich use of this force rather than the Essayist’s strict correctness.

The force itself is pre-poetic and forms an intense and unmediated natural language. Deeply felt things are the most difficult to describe, but this fact must not obscure the point that strange speech can arise from such depths if the need for expression is urgent, and we should thus embrace the use of language in the most living way. We need not belabor the point that authors must feel their language deeply in order to relate deep ideas, and many shadings of response must go into the selection of the right and moving words. We engage in pleonasm but not prolixity, and certainly not logorrhea.

We avoid inconcinnity without succumbing to sesquipedalianism. ” Grammar is a relatively simple matter with regard to relative clauses, the singular “they,” subjunctive mood, avoiding dangling participles, remembering to use possessive nouns before gerunds, knowing the principle parts of verbs, creating parallelism, and so on, or with regard to purely stylistic decisions, such as whether or not to use serial commas, hyphenate compound adjectives, or capitalize abstract nouns. Readers will quickly notice that we revel in compound subjects and verbs; that we get as excited as Lewis Thomas over semicolons; and that we would be speechless without transitional words and phrases. But due to the complexity and complicity of this work, we go beyond these grammatical problems in the volumes that follow, and could not rely upon a word processor to catch every error.

) Like all humans we err intermittently, but only sometimes. A method of literary expression utilized in this text, and uncommon in`,
      `modern academic works, is the extensive use of italics. While it has become fashionable for modern pedants to consider an abundant use of italics as “unprofessional,” the Noödynamics Institute sees this method as an extension of speech appropriate to words imbued with a livingness absent in the works of modern pedants. ” The divorce of speech from speaking required by the printed word devitalizes and rigidifies it, and makes it impossible to convey the whole truth intended. The replacement of verbal utterance and somatic gesture by purely grammatical word-significances is thus a decisive factor that can never be perfected.

There simply is no purely linguistic communication. The activity of communicating only with words, therefore, emerges more or less imprecise, and through every syntactical trick we must strive to evoke the significance-sense through the word-connections and the arrangement-forms. In other words, we must work diligently to surpass the abbreviated and indicative form-restrictions of perfect grammar in order to enhance word-relations with thought-relations. The readers need to “hear” what the writers mean.

Abstract thought consists in the use of a finite word-framework into which we must endeavor to squeeze the whole infinite content of life. The inner eye must triumph over the outer in the domain of the Noödynamics Institute: Grammar is for recording history; expression is for making it. “The man who could call a spade a spade should be compelled to use one,” quipped Oscar Wilde. ” This is not simply a grammatical matter, but is actually a logical matter—sometimes a grammatical subject in a statement is not the logical subject, depending on the purpose of the statement.

The presumption that the noun which is nominative to the principal verb in any statement indicates the logical subject delimits expressiveness. For example, if we take the statement “Art is creative,” ordinary grammatical analysis posits “art” as the subject and “creative” as the predicate. ”, then logical analysis posits “creativity” as the`,
      `” The relation of predication is an important way in which we connect significant ideas. The order in which words are used, the ways in which they are combined, and their inflections change the aura of understanding in and around them. History tends to remain in rich words as an immediate and intrinsic force, which the overly literal take as simply ornamental but the person sensitive to language recognizes as a moving example of human experience. Often, elaborate and even unnecessary words and word-use can dramatize a deeper meaning.

While pedants study dictionaries and manuals on “style” in order to make their speech precise, true wordsmiths, genuinely concerned with language’s living essence, realize that true style is a richness hidden in the deep truths of the human mind and mankind’s sense of the world-around. The person without some awareness of these qualities must inevitably remain insensitive to a substantial part of the intellectual life of the Culture. We choose our words not only, nor even primarily, for the rightness of their denotation but for the inter-connection of their connotations; not for their exactness to the “facts” but for the way they follow from other words in the passage. ” They are the meaning.

In short, it should be clear that a unified principle of selection is at work in the diction of these volumes, and that the language has been selected based on internal connotations and in response to the interplay of connotations, rather than based simply on denotation. S. Eliot wrote: Words strain, Crack and sometimes break, under the burden, Under the tension, slip, slide, perish, Decay with imprecision, will not stay in place, Will not stay still. Shrieking voices Scolding, mocking, or merely chattering, Always assail them.`,
      `For the same reason, we have also utilized the (mostly German) use of capitalization to indicate common words used to denote principles. We agree with Mark Twain, who declared that he had no respect for a person who could spell a word only one way. Cave homine unius libri

4 . Emphasis is crucial to human communication that colors meaning. The elimination of italicization and capitalization results only in terminological inexactitude. If we do not know around what point a sentence gravitates, we do not know the full meaning. Compare the subtle meaning-distinctions derived from the following sentences: We are fairly certain that our italics will enhance your reading comprehension. We are fairly certain that our italics will enhance your reading comprehension. We are fairly certain that our italics will enhance your reading comprehension. We have to know what is said lightly and what with significance; where a remark is prompted by quotation or repetition, it is ironical or a play on words; if something is allusion, cliché, parody, diatribe, and bold coinage, or intentionally ambiguous. That is the purpose of italics and capitalization—and the em dash, which as fans of Nietzsche’s meticulous style, we have also employed extensively. We recognize, in the words of that unorthodox grammarian, “that one must not be in doubt about the rhythmically decisive syllables, that one experiences the break with any excessively severe symmetry as deliberate and attractive, that one lends a subtle and patient ear to every staccato and every rubato, that one figures out the meaning in the sequence of vowels and diphthongs and how delicately and richly they can be colored and change colors as they follow each other....” (Consider how much better is Emily Dickinson’s poetry with her original idiosyncratic dashes and capitalization, eliminated by many editors.) A certain amount of Hermeneutics is required and requested herein.`,
      `This text has been written with a certain “poetic license” because the unvarying procedure of a dissertation would only help shield hyper-orthodox readers from serious challenges the text makes to established views. We wish to be, as a worst-case scenario, comprehended and then misunderstood. As Heidegger admonished, many paths through a forest may cross, or strangely disappear into the underbrush, right at that point where they offer illumination. Only a dialogue with the text, and subsequently with the Institute, will suffice.

A true engagement of a text is a methodology of faith seeking understanding—an axiom only repudiated in the 20th Century—and our modern Academics tend to be ignorant of faith and unwilling to understand that which defies the established logos. Our attempt to explore the dynamic tension between unitary intellectual activity and the pluralizing activities of emotion requires some quantum of Barthesian academic sensualism. ” Only thus can Nietzsche’s “Genealogy of Morals” be supplemented with a Moral of Genealogy. Ours is a metatropic quest, hence the text’s title.

Editors routinely eliminate the italics from works and thus often render them pages of dead letters. Perhaps a most notable example is Hegel’s Phenomenology of Geist, a text so full of life that only extensive italics could convey the energy of Hegel’s spoken words; but which has been reduced to mere print by most German and all English editors. As an entity specifically in defiance of the lifeless pedantry of modern Academia, the Institute has retained (indeed, encouraged) the original italics of the scholars who contributed material to the following text, and suggests that the message of a living wisdom is thereby more aptly offered. Those who disapprove may thus recognize an essential non-alignment with the Quest of the Noödynamics Institute, not one of mere form, and certainly not of “style”.

Consider a philosophical and/or scientific language; were it to be devised by a philosopher or scientist, he or she would do away with all inversions, synonyms, homonyms, expressive emphasis, and so on. He or she would attempt to devise a grammar that is mathematically precise. This would serve well in the presentation of doctrines and dry arguments`,
      `of proof, but would prove disastrous for use in, say, poetry (or even humor). The English of Shakespeare would be useless to a physicist or epistemologist, and our modern use of English would drive Shakespeare to despair. The pedants are incessant Gradgrinds, and thus prefer the merely descriptive to the rarely distinctive. They preach endlessly of economy of diction and its apparent clearness, over against the achievement of perspicacious predication and the complexity of compound clarity. In a nutshell, they loathe anything that by challenging the reader’s effort may raise his or her resistance.

For us, on the other hand, it is often better to choose the words that will tax minds the most. The ideal that the best way of writing is the easiest way to read is bourgeois, not academic, and we adopt the adage of the American pragmatist Horace M. Kallen, that a person is known by the vocabulary he keeps: The fundamental in every style is the rhythmic idiosyncrasy of its movement. Without that we could not possibly perceive the intent of thought, or get to the total significance of expression.

It is to speech exactly what it is to music. It generates and deposits words; which words is determined by the thought’s own pulse and cadences, that orders them as a magnetic flow orders iron filings or a stream carries leaves. In poetry this is obvious, or should be, particularly in the vers libre. In prose it is not so obvious, but it is none the less a fact. Eloquence need have no content; it works by infection, not signification; anybody who has heard a performance by the late Mr. William Jennings Bryan knows that.

The written word is even more dependent upon the transmission of the inward pulse for its effect, for it is not carried by a voice. Rhythm is characteristic, individual, the essence of personality in style…. Nor is this the end. The full, rich meanings which words have at the height of their significational function tend to`,
      `contract, even as their denotation tends to become irrelevant. The meanings compenetrate upon the point instead of expanding over the view of the point-of-view. They cease to awaken the intelligence to the perception of relationships and serve only to stir the emotion to irrelevant response. Instead of opening the doors of the mind upon visions, they lift the gates of the heart to feeling. Appreciation of them becomes habitual, reflex; their meaning is all in their sound.... The root of style is a theory of life whereby commonplace things are set in a cosmic perspective which is their meaning.

And, most efficacious and enduring, is the living word. Each time and people and person has his own, brought to birth by characteristic pulse and rhythm, and endowed thereby with its inward beat and outward pattern. For this reason, the style is not alone the man, the style is the age, the society, the civilization. By their styles shall you know them—the Elizabethans from the Georgians, the Victorians from the moderns, the moderns from all. In the measure of their prose and verse, in the vistas of their vocabularies, in the appreciations and condemnations of their value-words, are revealed their secret hearts and publis mundi, all that they fear and hope for themselves and mankind at work upon an experience they are bringing to order and excellence by binding with words, by giving it, that is, meanings.

One major problem with discussions of an academic nature is the meaning of the words we use as terms; we must try to ensure that writers and readers attach the same meaning to terms used. But in a cultural discourse, words are often signs and symbols through which ambiguous meanings are conveyed. We cannot talk with analytical precision unless in our minds we use words with analytical precision. But when dealing`,
      `with subjects of a meta-analytical nature, some latitude is required. Thus in this text, which necessarily alternates between analysis and synthesis, we have had as our primary concern an internal consistency. To understand one another meaningfully, it is necessary that each attach the same meaning—precise or ambiguous—to the same word. This internal consistency, we feel, will avoid as much confusion as possible in our use of the signs and symbols with which we classify, categorize, and define principles and concepts in our mind.

In most academic studies, most of the words used as terms are peculiar to that study. The terms used in Physics, for example, are typically used only in Physics, or used in the Physics terminology when used elsewhere. But the terms used in The Phenomenology of Culture-Systems are not words reserved to it; many are words in everyday use. In studying The Phenomenology of Culture-Systems, in thinking out its issues, then, it is absolutely necessary to give such terms as culture, phenomenology, soul, spirit, consciousness, life, spirituality, art, mind, materialism, and so on, a consistent meaning if we are to maintain academic integrity; and we must use them only for this meaning.

We feel we have accomplished this task, and may thus avoid the liability to confusion found even in most eminent writers on Culture, confusing themselves as well as their readers. In cases where common meanings tend to differ—and in some instances to differ widely—from those assigned herein, we have set forth our definition with the first use of this word.`,
      `A minimum qualification of good language is the ability to find words that exactly describe the intended phenomenon. The least that one can expect of language well used is a certain precision in such choices. Often, however—and it is the case here—writers find that the words they seek do not exist ready-made, and they must force words to perform duties not normally expected of them. Hence have we made much use of the German tradition of combining words to get new compound words with unique meanings.

Such wrenchings of one part of speech into another can at times seem forced, but we have striven for exactness without strain. ” Matters of Philosophy and Science have as their major purpose the correctness and clarity of concepts. , have as their major purpose the embodiment of expression and beauty. Perfection and beauty are not necessarily synonymous. Whereas the major purpose of the Noödynamics Institute is to bridge this gap as much as can be accomplished without detracting`,
      `from either side, its methodology is unique to both domains. The reason for the regrettable length of this multi-volume text is that its theses cannot be simply stated; they must be rendered, to borrow a famous concept from Henry James. The rendering necessarily becomes a labyrinth with Truth as its center. We have attempted to approach an “art” of Culture Criticism, aesthetically interpreting the semiotic world. We have been liberal with grammar and style because we want this text to be an abridgment of a thousand years of history in the West; a survey in compact scope of the salients and prominences of the massive output of the culture-system.

This text cannot be the whole—and so is less—but it contains the promise of the whole. It will renew one’s knowledge of the terrain, and/or lead one to explore it more fully. Cultura longa vita brevis. There are many questions this text will try to answer. And in answering these questions it will sketch a family portrait, that of the West, a picture of a culture-system with its own character, its own memories, its own stories. Some of the stories are familiar to many; other stories, including some of the best and most important, remain mostly unknown.

And one good reason for compiling a text like this one is to tell those stories to a new generation that may find in them a reason to be proud. If we listen to these stories as a kind of symphony, we can discover recurrent themes, sometimes played in minor key, at other times transposed into a single major chord, all accompanied by variations on a theme. This is a text that we have always wanted and needed to read but which was not written—so we wrote it. It is extremely difficult, not to say impossible, to write a comprehensive introduction to the West as a culture-system.

One must present a living, organic whole with the simple and sure master strokes that are the despair of professional historians and philosophers. Yet we believe we have succeeded to a sufficient degree, such that those who read the present text will see a true and vibrant Western Culture emerge from its pages. They will catch the spirit of the culture-system, the spirit and the grandeur. Here is a dramatic description of what most historians and philosophers treat in a most undramatic way—Being.`,
      `This is a very eclectic text, bringing together diverse fields of knowledge through the words of many talented persons—a task requiring no little effort of organization and coordination; naturally, such an undertaking is bound to present some overlooked errors and/or inconsistencies, although the latter would likely be more apparent that real. Our hope is that a succession of attentive readers will recognize and indicate such, so that the text may be continually improved. “The Poem is never finished,” said Paul Valery, “only abandoned.” We have had the unenviable task of developing a text that is traditional in scope but contemporary in perspective, which is eminently difficult when topics are fundamentally eclectic and jargon-laden. Because our aim is all literate (but not necessarily academic) individuals, we have supplemented the text with a plethora of primary sources. The result is, we think, an accessible but solid introduction to our main propositions, vividly illustrated with educational material. All our myriad quotations are presented not in the name of “authority,” per se, but in the name of contingency. Dramaturgy is not, as E.M. Forster poignantly explained, the relating of mere sequences of events: “The king died, and then the queen died.” Rather, it is the relation of episodic contingency: “The king died, and then the queen died of grief.” Not “What then?” but “Why?” defines our inquiry. Our history is not a collection of threads or even a rope, but a tapestry. We embrace a Coleridgean faith in the unity of knowledge. Conversely, as a very eclectic and complexly constructed tome, this text offers its myriad supplemental parts in a truer context than the average document of similar depth and diversity—its many quotes, for example, derived from many sources, are taken from respective texts, rather than from a volume of Bartlett’s Familiar Quotations, as is common in an increasingly superficial and pedantic Academia. “A classic,” noted American wit Mark Twain, “Is something everybody wants to have read and nobody wants to read.” Proust’s Remembrance of Things Past (1913-27), for example, despite being referenced in countless academic works, has actually been read by almost no one alive today—and most of the exceptions are members of the Noödynamics Institute.

5 This text also contains none of`,
      `the disgusting quilt quotations so common in modern scholarship-cum-propaganda. We have tried, where not uncomfortable, to compensate for the absence in English of a generic word for human being. ” We simply utilize the technically ungrammatical “they” and “their” to avoid such problems. Nevertheless, we have found the use of “man” indispensable: we use it in its scientific sense, including both sexes in general as Homo sapiens. We have noticed, with University of Colorado humanities professor Althanasas Moulakis, that many mechanical corrections of the apparently male designation of “man” are not only clumsy but misleading.

He wrote, with typical brilliance: What is needed is a mastery of language, that is, a grasp of its force and of its ambiguities, not the tuning of a few knobs. ” Helping students develop a habit of thinking of women and men when they think of “humanity” is entirely a good thing but the most meticulous and tedious use of “she/he” will not prevent them from developing substantively sexist ideas and may, in fact, mislead them into thinking that that kind of tokenism is all it takes to overcome prejudice. The more absurd cases of changing evocative sounds of words, regardless of Etymology, in an attempt to overcome false consciousness, as in “her story” for the study of the past from a female perspective, are again predicated on the presumption that the public is ignorant and is bound to remain so and is—much like refusing to wear fake furs because it might encourage those who can’t tell the difference to wear real ones—a combination of self-righteous presumption and barbarism,`,
      `but the widespread practice of mechanical “gender-neutrality” in writing is symptomatic of the superficiality that goes with wearing one’s skeleton on the outside. We also state emphatically and unapologetically that we have not given much thought to the so-called “political implications” of the scientific ideas explored herein. The reason for this is simple and honest: We don’t care. The last truly charming bohemian, the flamboyant Hibernian Oscar Wilde admonished: “There is no such thing as a moral or immoral book. Books are well written, or badly written. That is all.” We have engaged in sincere, honest, credible, and apolitical fact-finding, model-making, and model-observation matching, ‘implications’ be damned. The truth as revealed by Science is the truth, regardless of “cooking.”

6 If the truth “hurts,” it is still the truth. We are “planters,” not “weeders,” and so any moral reading

7 of this text by Politicians-qua-Academics

8 will be dismissed as not only irrelevant, but as anti-intellectual. When Academics go outside their domain and start concerning themselves with the so-called “political implications” of truth, the result is always half-truths or the bending of Truth to fit sociopolitical agendas. The outcome of such distortions is often even a reversal of cause and effect in intellectual pursuits, in which conclusions are set forth and then facts are sought for support; all other facts are then deemed “bad science.” From the Church at the time of Copernicus and Galileo to the Marxist Critique at the advent of the IQ and Sociobiology debates in the 1970s and 80s, such thinking is always inherently supernatural. The only ideas we critique more steadfastly than those we despise are those we admire. Hence we forego introducing strictures with insults or apologies. If we tried to swim against the current making atonement for every meter gained, we would get nowhere. If we succeed in reversing the stream only to discover that no good is seen in those ideas we critiqued, there will be enough time for embarrassment later, and for reconciliation. Hence we speak out boldly but retain sufficient compassion to recognize in those we oppose many virtues lacking in those we condone, not to mention in ourselves. Being right is less`,
      `” We do not, as so many of our detractors will, engage in the dishonorable practice of apophatic rhetoric. Although some of the ideas expressed below may be deemed radical, none is too radical for conceivability. In fact, we feel that the solutions and resolutions proffered, despite their unconventionality, could resolve some of the inconsistencies of orthodoxy. We do not deal in absolutes, but do attempt to make propositions with tremendous implications for our collective view of existence, and thus we have tried to be bold without being immodest.

We do not want to entertain with countless amusing anecdotes, titillate with mind-bending verbal paradoxes, or evoke moods of exalted confusion with exaggerated metaphor. But we also refuse to adopt middle-brow sensitivities and preach to publicans. ” If you sense a gigantism and triumphalism running through sections of these volumes like a Wagnerian motif, then you have intuited our point of view. A sense of tragedy haunts other sections of these volumes, but it does not enter into them. We are men and women of unborrowed vision whose cri de coeur is to strive for a position that is not burdened by decades of senile and parasitic bureaucracy; a position untempered by generations of social engineering; unattenuated by innumerable vulgar promises to countless special-interest groups; and uncorrupted by a cynical contempt for intellectual honesty, academic integrity, and cultural dignity.

Science offers truths and Politics offers opinions. While the latter may—and we say should—be predicated upon the former, the former must never be restricted or biased by the latter. This is merely a logical extension of the inductive method at the root of Science per se. The application of scientific theories is a legitimate area for political debate. Debates over research, however, are pseudo-debates and result only in pseudo-science. Science is not about choice but about knowledge. Only`,
      `after such knowledge is acquired can choices about its usefulness and application become topics of legitimate discussion. The fraud inherent in modern Academia’s conclusions-based pseudo-intellectuality exposes a severe lack of faith in the principles of Democratic society these scientific policemen always claim to represent. Science genuinely “for the people” is Science unrestricted by special-interest groups from the Left or Right wings of the political spectrum. In recent decades, both Neoliberals and Neoconservatives have done significant damage to the West’s scientific quest.

We agree with the apolitical defender of academic freedom, Bernard Davis: I believe we will... need a restoration of trust in the scientific community. For scientists have a remarkable record of professional honesty and responsibility—not because they are inherently more virtuous than other citizens, but because neither they nor their world gain from their research unless their actions and findings are made public, subjected to minute scrutiny by peers, and found to be verifiable. Moreover, as an intensely communal, critical activity, science has developed finely honed mechanisms for evaluating controversies dispassionately, and with emphasis on evidence and logic rather than on rhetorical skill and public stature.

It is difficult for the public to make such distinctions.... Of late, perhaps because of guilt over the charge of elitism and the ills of technology, some scientists appear to be losing confidence in the objectivity of scientific knowledge and in the ability or the right of their community to speak with any authority. But while there is no room for absolute authority in science, there is also no room for extreme intellectual relativism. In the areas of its expertise and the obligation, to help the public to discriminate between rational and irrational views.

Finally, this text is not, as some would expect, formatted pursuant to the rigid structure of a doctoral thesis; rather, it is offered more as part of`,
      `the Institute’s hope to strip Science and Philosophy of their rigid pedantry, and imbue them with the livingness of Spirituality and the Arts. For example, we have violated the grammatical rule that “should” replaces “would” in first-person usage, because it is pedantically confusing: “would” is commonly understood to denote potential, while “should” is understood as imperative. Thus this rigid pedantry detracts from a work, where rules of grammar should improve it. Ernest Vincent Wright wrote a fifty-thousand word lipogram in 1939 (Gadsby) without using the letter “E,” and Georges Perec also wrote an E-Less lipogram (LaDisparition) and a book containing only “Es” (Les Reventes), but no one has proposed this to be proof of the superfluity of certain letters in language.

We loathe and reject the pop-culture slang used by many “hip” academics, but within the constraint of academic English, we use the forms that are most expressive rather than those which demonstrate that we belong to the small group well-versed in Strunk and White’s Elements of Style (1959). We have mostly disregarded the MLA Handbook For Writers of Research Papers and the Publication Manual of the APA as part of an ingenious attempt to better accommodate the non-academic reader with an academic syllabus, and because we do not seek imprimatur. W. Fowler.

As F. ” While we refuse to descend into the miasma of modern “style,” we also refuse to adhere to outmoded rules which limit expressiveness; our subject is not only serious and significant, but it is novel, and likewise, our “style” is serious, significant, and novel. Just as motion cannot be detached from a body, nor the dance from the dancer, so style cannot be detached from prose. As the best-selling language buff for the New York Times Magazine, William Safire, once noted: There is a big difference between being conscious of your language and being self-conscious about the way you write`,
      `and speak. To be conscious of language is to be proud of the magnificent and subtle instrument in your hands; to be self-conscious about the possibility of error, or fearful of the derision of your listener at your experiments with the instrument, is to be a nerd, a schnook, and a wimp. The pertinent question, it seems, is less about the use of idioms than about arrogance and pedantry in academic language use; is this pseudo-elitism caused by ignorance of or apathy for the dynamics of expression? Quite frankly, we don’t know and we don’t care.

We do not hesitate— where appropriate, of course, and without attempts at showiness—to use epanalepsis. We like, nay, we love epanorthosis. And we are not averse to litotes. We might be so bold as to occasionally split an infinitive, but never so callous as to end a sentence with a preposition. That is the type of grammar up with which we will not put. For the above and similar reasons, most of the translations in the volumes below are original. Translation can be compared to transposition in music; compared to playing a tune composed for violin on the piano.

It is not merely a question of fine-tuning and a distinct technical mastery, but a translation of notes, tone, voicing, timbre, register. The piano really does not speak the language of the violin at all, and thus a pidgin results. ” As Croce advised: Indeed, every translation either diminishes and ruins, or it creates a new expression, by putting the former back into the crucible and commingling it with the individual impressions of the so-called translator. In the former case, the expression always remains unitary, that of the original, the translation being more or less deficient, that is to say, not properly expression: in the other case, there will certainly be two expressions, but with two different contents.

As Borges pointed out long ago, translation has not just literary`,
      `problems but also philosophical and aesthetic problems—there are inter-linguistic and intra-linguistic difficulties, the latter representing an issue analogous to the former when one epoch translates another. We agree with Borges that a translator must possess some quantum of hermeneutical empathy in order to render a quality transliteration, and that he or she must be capable of a modicum of productive distancing. We have thus taken into account specific discursive strategies in the translated portions herein. We have sought above all to reconstruct the full intentional quality of every passage while not succumbing to the temptation of anachronistic projection, always keeping in mind that translation is in many ways an art, and as such is a triadic endeavor: (1) original text; (2) translator as mediator; and (3) new version.

Rather than abiding by a word-for-word pedantry, we have attempted to “see-into” linguistic forms, with the full recognition that total linguistic transparency is neither possible nor necessary. In order to fulfill the first-order purpose of the translations below, we have taken certain liberties of extrapolation which, we feel, offer the most contextually viable presentation. Reading a translation is, after all, as Cervantes pointed out, like looking at the back of a tapestry. We have, therefore, been everywhere guided by the theme of original texts but nowhere misguided into mere paraphrase, focusing on the pragmatic conditions of thematized linguistic exchange.

e. ” Many, probably most, translations suffer from a noncontextuality and dethematization due to the incomplete understanding of the translators, and so many of the most important ideas in history have been rendered essentially unintelligible. Thus have we attempted to restore the full significance of various concepts in order to better represent expressive intent. The pragmatic dimension of language demanded in the volumes which follow overrides any desire for syntactically precise and objective renditions with an ideal of creative translation with normative`,
      `commitments. We have, a priori, accepted the inescapable fact of the influence of our intellectual interests and worked to diminish distortions by perceiving the translations as a form of discourse. What is involved here is, after all, more than an abstract search for facts and/or a systematic presentation, and so our translations have been effectively rendered as elements of a metanarrative. The following thesis is not neutral but circumscribed and determined by the discursive strategies of the Noödynamics Institute, and its translated passages have been incorporated into this generalized schema, homoglossia having been a constitutive aspect of the final text.

We have kept in mind Gadamer’s advice: Every age has to understand a transmitted text in its own way, for the text is part of the whole of the tradition in which the age takes an objective interest and in which it seeks to understand itself. The real meaning of a text, as it speaks to the interpreter, does not depend on the contingencies of the author and whom he originally wrote for. It certainly is not identical with them, for it is always partly determined also by the historical situation of the interpreter and hence the totality of the objective course of history. We write in a style that is neither fashionable nor profitable in a society presently under the delusion that journalism is creative writing.

We reject, however, the use-value approach to style, and cannot renounce a poor investment if it be one of quality—indeed, we were tempted to accept universal calumny and publish in Gaelic. Fili oga. ” B’aistriúcháin muid caillte sna spásanna idir focail ag lapadail archulithe briathra. Sruth teangacha, spré don aonarán rachaidh mé leis an sruth. What is most difficult to render from one language into another, or in the present case, from many languages into one, is the unitary tempo of`,
      `the variegated style(s), which has its basis in the character of the native language, or, to utilize psychophysical terminology, the average tempo of its cognitive metabolism. The deep “physiognomy of the soul” (Schopenhauer) is somewhat lost in translation. Of course, we would have liked to write this entire text in iambic pentameter in three-eighths time: Le style est l’homme. We will undoubtedly be asked why, after all, we publish in English, when we shall be nowhere read worse than in the English-speaking nations.

Our “lingua franca” is, inevitably, lingua anglica, but this was a purely pragmatic decision without deeper meaning. The English language, nevertheless, suits our purposes, in that it possesses the most words—over a million—and words are the basic data of semiotic consciousness. English is not an inflected language, relating a complex of concepts by the modification of words, but instead utilizes auxiliary verbs and prepositions to greatly increase explicitness. This generates a more complete and expressive conceptualization of the complex ideas involved.

The language capable of communicating the most and finest meanings is best, and various languages—especially Russian, Italian, German, and French—would be best for the various volumes which follow. But we are not building a tower of Babel, and so we have taken the path of least resistance and settled upon the one language spoken in every Western nation. In our desire to create a bildungsroman and roman à clef, we strive to be luminous rather than voluminous. The richness of inflection in the verbs, the frequency of particles and conjunctions, the exceptional condensation and transposition of which it is capable, make English’s effects full of genius and capacity of expression.

Italian is probably the best of all languages in melody, richness, elasticity, and simplicity; so much so, that in spite of its complex inflections, when once a vocabulary is acquired, it is more easy and natural than beloved French. French is by nature the stiffer tongue, at once laconic and grandiloquent. Both, however, lack the inimitable interpenetration of English, with its unique power of synthesizing phrases. The atomic character of the words and the flat juxtaposition of the`,
      `clauses are more than compensated in the wealth of suggestion and the refinement of sentiment. In the 17th Century the Academie Francais gave up the use of Latin in its publication of proceedings in lieu of French, inspiring the Academies of Science in Germany and England to also publish in their own languages, forcing the pan-European scientific community to adopt an “official” language for Science. English was eventually chosen and so we follow suit. Especially in dealing with historical doctrines of Philosophy, some academic forbearance is requested, because the present text often dissects them into component elements for its own purposes and recombines diverse ideas from diverse doctrines into what is considered a congruent whole.

The reason for this is simple, if controversial: the vast sequence of philosophical systems which fills Western textbooks is bewildering to students due to the multiplicity and duplicity involved. Yet in reality, the majority of arguments in this myriad diversity are second and third order statements—predicated upon a very limited number of essentially distinct first order principles. A novelty of arrangement and application, not genuine multiplicity of core elements, is the cause of the enormity of philosophical text material —an unnecessary duplicity which academic pedants embrace and aggravate. We believe that the interweaving of the diverse philosophical doctrines herein—doctrines hitherto presented as mutually exclusive under the guise of various classification systems (isms)—sufficiently demonstrates this fact and justifies the academic liberties taken in the present text.

As founder of the American Association of University Professors and Johns Hopkins philosophy professor Arthur O. Just as chemical compounds differ in their sensible qualities from the elements composing them, so the elements of philosophical doctrines, in differing logical combination, are not always readily recognizable; and, prior to analysis, even the same compiles may appear to be not`,
      `the same in its different expressions, because the diversity of the philosophers’ temperaments and the consequent inequality on the distribution of the emphasis among the several parts, or because of the drawing of dissimilar conclusions from partially identical premises. To the common logical or pseudo-logical or affective ingredients behind the surface-dissimilarities the historian of individual ideas will seek to penetrate. In the present text, because it is not a history of individual ideas but rather a search for the homology of diverse culture-expressions, we have dissected and recombined various philosophical component elements of the Arts and Sciences as well. We feel that in undertaking this work, we have succeeded in offering a glimpse into the ultimate unity of diverse expressions while not violating the spirit of individual disciplines.

As American philosopher Justus Buchler noted: A system is kindled, in other words, not by a desire to give answers to standing problems, but by a demanding form of awareness that requires conceptual ramification. Inevitably, specific problems are coped with by both those which the new mode of discrimination itself breeds and those which it construes as the traditional. The very source of a system’s problems lies in its gestation and application: there are discrepancies among its assertions, there is darkness in the evolving portrayal; the scope of its categories recurrently becomes uncertain; the categories need clarification. As Thomas Kuhn demonstrated, paradigm shifts often result from the great unifications of formerly disjointed fields of knowledge rather than the introduction of new knowledge.

“There are books of the same chemical composition as dynamite,” advised the Russian satirist Eugene Zamiatin. ” The academically unorthodox methods delineated above are`,
      `necessitated by the fact that the central insight of a New Era is a thing to be reached not through a consecutive progress of merely rational thought guided by the ordinary logic of the past two and a half centuries, and certainly not through Academia’s logomania, but rather through a quantum leap whereby one rises to a plane of insight wholly different in principles from the level of Old Era understanding. ” As modern American philosopher Robert P. Pirsig noted almost thirty years ago: The real university is a state of mind. It is that great heritage of rational thought that has been brought down to us through the centuries and which does not exist at any specific location.

It’s a state of mind which is regenerated throughout the centuries by a body of people who traditionally carry the title of Professor, but even that title is not part of the real university. The real university is nothing less than the continuing body of reason itself. Unless one is in some sense able to transcend Western history, to be reborn into a New Age, one cannot acquire the existenz which is the secret of the New Millennium. ” This text was so written and what here shall miss, our toil shall strive to mend.

This text was conceived during the conjunction of Jupiter and the Moon. C. and 1997. ” It was either this or 42. S. ” And who is sure in the end that we even wish to be read today? To create a tome upon which time will test its teeth in vain; in form, in`,
      `substance, to strive for eternity—we are not modest enough to demand less than a Nietzschean task of ourselves. These volumes are the forms of our desire for immortality; it is our ambition to summarize in several volumes what myriad have put forth in a millennium—what no one else has summarized in our era. These forebears have given Mankind the most profound knowledge it possesses; now we have given it the most integrated and coherent, concise version. Aere perennius. And perhaps we could whisper something to our Good Europeans whom we love as much as we— Out of this affection, we remain humble despite a mbition. It is probably true that no individual or group of individuals could compose a book, in isolation and based on original ideas, that would so move readers that their way of life would be changed. But we believe it is possible for a group of individuals, working in inspired cooperation, to set down in precise form what is vaguely, from a thousand disparate sources, already in great minds, and in doing so, change the course of history. Like Chaucer’s scholar we would rather have a hundred books than any other wealth the world can offer; and like Aquinas we thank the Gods most for the fact that we have understood every page we have read. We adopt the Voltairean principle that the great should be elevated and the infamous crushed, but the hands which do the elevating and crushing should remain unknown. Hence we publish anonymously. We prefer Foucaultian author-functions to flesh-and-bone authors: La mort de L’auteur. In the United States, the First Amendment of the Constitution protects individuals’ right to speak anonymously.

9 An author’s decision to remain anonymous is an aspect of the freedom of speech protected in some manner in all Western nations. “The name of a man is like his shadow,” advised the Viennese onomatologist Ernst Pulgram. “It is not of his substance and not of his soul, but it lives with him and by him. Its presence is not vital, nor its absence fatal.” We’re the hand that writes and quickly moves away. (Dio)`,
      `Turn, Please by Sandro Del-Prete We are not simply attempting to construct one out of several possible merely logically justifiable treatises; we are striving for the philosophical treatise of the 21st Century—thus what follows is essentially a historical naturalism which has been more or less presaged by every great heart and mind of the last ten centuries. We state this without the presumption it could imply, since an idea of such grandeur is culturally predicated—it does not occur “within” a time, incidentally, but itself makes a time what it is—and hence is the property of no individual or group, even if they necessarily gave it form. This treatise, therefore, belongs to our Civilization and our era as a whole. Thy praise or dispraise is to me alike`,
      `One doth not stroke me, nor the other strike

10 ©1997-2018, Noödynamics Institute. All rights reserved under Universal, Berne, International, and Pan-American Copyright Conventions, and Article 27 of the Universal Declaration of Human Rights adopted by the U.N. General Assembly on December 10, 1948. However, pursuant to Title 17 U.S. Code, Section 106 of the Copyright Act, any part of this text may be reproduced, displayed, and/or distributed for academic and informational purposes, without prior written permission, so long as such is done free of charge and the material is no more than 10 pages, has been neither edited nor abridged, the Institute is credited, and a copy of the material or a link to it is provided to the Secretary. The following fruits of intellectual labor, as the product of a unitary civilization, cannot be legitimately deemed private property, and so are essentially the common property of the Western culture-system as a whole. The invocation of copyright protections, therefore, is intended only to protect this resource. No portion of the text may be thus used in altered form (including translations, web distribution, information networks, or information storage and retrieval systems) without prior written permission from the Director of the Institute. Of course, reproduced material may be protected by original copyrights. ________________

1 Ben Johnson, “To The Reader” (1616)

2 The Hunchback of Notre Dame.

3 Spenser

4 “Beware the man of one book”

5 Year dates appear, sometimes again and again, to give the reader unfamiliar with certain authors or works a chronological sense, and where appropriate, to make each chapter and volume more or less independent of others in such matters.

6 Babbage, 1830

7 Segerstrale, 2000

8 q.v. Boas, Montague, Lewontin, Hubbard, Rose, Kamin, Alper, Levins, Beckwith, Layzer, Block, Dworkin, Luria, Tobach, Poshansky, Stagner, Vetta, Kitcher, Gould, et al.

9 See McIntyre v. Ohio Elections Commission, 514 U.S. 334, 342 (1995)

10 Ben Johnson, To Fool or Knave (1616)`
    ],
  },
];
